#!/usr/bin/env perl
use Mojolicious::Lite;

use feature 'signatures';

plugin Config => {file => app->home->rel_file('config')};

get '/' => sub ($c) {
    $c->render(template => 'index');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
<h1>Welcome to the Mojolicious real-time web framework!</h1>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
    <head><title><%= title %></title></head>
    <body><%= content %></body>
</html>
