#!/usr/bin/env perl
use Mojolicious::Lite;

use feature 'signatures';
no warnings 'experimental::signatures';

plugin Config => {file => app->home->rel_file('config')};
my $api_base = app->config('api')->{base_url};

# Detect proxy setting from environment
app->ua->proxy->detect;

# Load mensa data including Google Maps link
sub load_mensa_data ($id) {

    # Request and parse JSON
    my $url     = "$api_base/canteens/$id";
    my $data    = app->ua->get($url)->result->json;

    # Build Google Maps URL
    my $gm_url = 'https://www.google.com/maps/place'
        . "/$data->{coordinates}[0],$data->{coordinates}[1]";

    # Done
    return {
        %$data,
        api_url         => $url,
        google_maps_url => $gm_url,
    };
}

# Homepage: redirect to listing
get '/' => sub ($c) {
    $c->redirect_to('list');
} => 'home';

# List all known mensa items for selection
get '/list' => sub ($c) {

    # Retrieve data for each mensa (synchronously, sorted)
    my @mensa_ids   = @{ $c->config('mensa_ids') }; # deref array ref
    my %mensa_data  = map {$_ => load_mensa_data($_)} @mensa_ids;
    my @mensa_data  = sort {$a->{name} cmp $b->{name}} values %mensa_data;

    # Done
    $c->stash(mensa_data => \@mensa_data);

} => 'list';

get '/mensa/:id' => [id => qr/[0-9]+/] => sub ($c) {
    my $mensa_id = $c->param('id');

    # Load mensa base data
    my $mensa_data = load_mensa_data($mensa_id);

    # Load meal data
    my $meal_url    = "$mensa_data->{api_url}/meals";
    my $meal_days   = $c->app->ua->get($meal_url)->result->json;

    # Process days
    for my $day (@$meal_days) {

        # Date: transform 2018-11-23 to 23.11.2018
        $day->{date} = "$3.$2.$1"
            if $day->{date} =~ /^(\d{4})-(\d\d)-(\d\d)$/;
    }

    # Done
    $c->stash(
        mensa_data  => $mensa_data,
        meal_days   => $meal_days,
    );

} => 'mensa';

app->start;

__END__
